// Generated from the backend migrations (role_permission grants, both insert styles).
// Regenerate when the grants change; the mock must never grant more than the database.
export const GRANTS = {
  CENTRAL_ADMINISTRATOR: 'appointment.approve appointment.assign_doctor appointment.assign_room appointment.assign_team appointment.cancel appointment.mark_no_show appointment.read appointment.read_own appointment.reject appointment.reschedule audit.export audit.read centre.activate centre.create centre.read centre.read_own centre.update centre_bundle.mark_treated centre_bundle.read centre_capability.manage centre_patient.create centre_patient.read centre_patient.update centre_referral.read centre_report.read clinical_note.read config.read config.update consent.manage_versions consent.read consultation.read consultation.switch_modality consultation.terminate doctor_availability.manage doctor_availability.read document.download document.issue document.read document.read_own document.revoke ehr_import.activate ehr_import.read ehr_import.upload ehr_verification.resolve enrolment.release_code finance_report.read follow_up.read follow_up.read_own investigation.read investigation.read_own mfa.reset notification.manage_templates notification.read_own notification.send patient.activate patient.create patient.flag_drift patient.read patient.read_own patient.update patient.verify payment.exception_handle payment.initiate payment.read payment.read_own payment.reconcile payment.refund prescription.read prescription.read_own profile.read_own profile.update_own queue.him queue.nursing recording.read recording.start release_bundle.read release_bundle.release review.read review.submit_to_hub role.assign role.read room.manage room.read schedule.publish schedule.read session.revoke slot.read supervision.read_log supervision.view_as system.health_read ticket.assign ticket.close ticket.create ticket.escalate ticket.read ticket.read_own ticket.respond triage.read upload.create upload.delete upload.quarantine upload.read user.create user.deactivate user.read user.reset_password user.update vitals.read vitals.verify wallet.credit wallet.read_balance wallet.read_ledger',
  CENTRE_ASSISTANT_COORDINATOR: 'appointment.read_own appointment.request centre.read_own centre_bundle.read centre_patient.create centre_patient.read centre_referral.create centre_referral.read centre_report.read consultation.join_as_centre document.read_own notification.read_own profile.read_own profile.update_own schedule.read slot.read ticket.create ticket.read_own upload.create upload.read upload.read_own vitals.submit',
  CENTRE_HIM: 'centre.read_own centre_bundle.mark_treated centre_bundle.read centre_patient.read centre_patient.update centre_report.read document.read_own notification.read_own profile.read_own profile.update_own ticket.create ticket.read_own',
  CENTRE_HUB_COORDINATOR: 'appointment.cancel appointment.read_own appointment.request appointment.reschedule centre.read_own centre_bundle.mark_treated centre_bundle.read centre_patient.create centre_patient.read centre_patient.update centre_referral.create centre_referral.read centre_report.read consent.accept consultation.join_as_centre consultation.read document.download document.read_own notification.read_own profile.read_own profile.update_own schedule.read slot.hold slot.read ticket.create ticket.read_own upload.create upload.read upload.read_own vitals.submit',
  CENTRE_LABORATORY: 'centre.read_own centre_bundle.mark_treated centre_bundle.read centre_patient.read document.download document.read_own investigation.read notification.read_own profile.read_own profile.update_own ticket.create ticket.read_own',
  CENTRE_PHARMACY: 'centre.read_own centre_bundle.mark_treated centre_bundle.read centre_patient.read document.download document.read_own notification.read_own prescription.read profile.read_own profile.update_own ticket.create ticket.read_own',
  DOCTOR: 'appointment.read centre_patient.read centre_referral.read clinical_note.read clinical_note.sign clinical_note.write consent.read consultation.join_as_doctor consultation.read consultation.switch_modality consultation.terminate doctor_availability.read document.read follow_up.read follow_up.write investigation.read investigation.write notification.read_own patient.read prescription.read prescription.write profile.read_own profile.update_own recording.start review.read schedule.read ticket.create ticket.read_own triage.read upload.read vitals.read',
  FINANCE: 'appointment.read centre.read finance_report.read notification.read_own patient.read payment.exception_handle payment.read payment.reconcile payment.refund profile.read_own profile.update_own ticket.create ticket.read_own wallet.credit wallet.read_balance wallet.read_ledger',
  HELPDESK: 'appointment.read enrolment.release_code notification.read_own payment.read profile.read_own profile.update_own system.health_read ticket.assign ticket.close ticket.create ticket.escalate ticket.read ticket.read_own ticket.respond user.read',
  HIM: 'appointment.read document.read ehr_import.activate ehr_import.read ehr_import.upload ehr_verification.resolve enrolment.release_code notification.read_own patient.flag_drift patient.read patient.verify profile.read_own profile.update_own queue.him ticket.create ticket.read_own',
  HUB_COORDINATOR: 'appointment.approve appointment.assign_doctor appointment.assign_room appointment.assign_team appointment.cancel appointment.mark_no_show appointment.read appointment.reject appointment.reschedule centre.read centre_patient.read centre_referral.read clinical_note.read consent.read consultation.read doctor_availability.manage doctor_availability.read document.read ehr_verification.resolve enrolment.release_code follow_up.read investigation.read notification.read_own notification.send patient.read patient.verify prescription.read profile.read_own profile.update_own release_bundle.read release_bundle.release review.read room.read schedule.publish schedule.read slot.read ticket.create ticket.read_own triage.read upload.read vitals.read',
  ICT_SUPPORT: 'config.read ehr_import.read ehr_import.upload ehr_verification.resolve mfa.reset notification.read_own notification.send profile.read_own profile.update_own session.revoke system.health_read ticket.create ticket.escalate ticket.read ticket.read_own ticket.respond upload.delete upload.quarantine user.read user.reset_password',
  LABORATORY_TECHNICIAN: 'appointment.read centre_patient.read document.read investigation.read notification.read_own patient.read profile.read_own profile.update_own review.laboratory review.read review.submit_to_hub ticket.create ticket.read_own upload.read vitals.read',
  NURSING: 'appointment.assign_room appointment.read notification.read_own patient.read profile.read_own profile.update_own queue.nursing room.read ticket.create ticket.read_own vitals.read vitals.verify',
  PATIENT: 'appointment.cancel appointment.read_own appointment.request appointment.reschedule consent.accept consultation.join_as_patient document.download document.read_own follow_up.read_own investigation.read_own notification.read_own patient.read_own payment.initiate payment.read_own prescription.read_own profile.read_own profile.update_own schedule.read slot.hold slot.read ticket.create ticket.read_own triage.submit upload.create upload.read_own vitals.submit',
  PHARMACIST: 'appointment.read centre_patient.read document.read notification.read_own patient.read prescription.read profile.read_own profile.update_own review.pharmacy review.read review.submit_to_hub ticket.create ticket.read_own upload.read vitals.read',
}
