import '@/features/patient/gateway.css'
export function Landing() { return <div className="gateway-experience gateway-page">
  <div className="safety-ribbon"><strong>Safety first · non-emergency service</strong><span>For immediate danger, severe agitation or acute psychosis, seek urgent in-person care.</span><a href="tel:112">Emergency 112</a><a href="tel:08032722243">FNPH 24/7 support: 0803 272 2243</a></div>
  <header className="site-header gateway-header"><a className="brand" href="/" aria-label="FNPH Kaduna Telepsychiatry home"><img src="/fnph-logo.png" alt="Federal Neuropsychiatric Hospital Kaduna logo" /><span><strong>FNPH Kaduna</strong><small>Telepsychiatry access portal</small></span></a><div className="header-actions"><label className="language-gateway"><span aria-hidden="true">文</span><select aria-label="Choose language"><option>English</option><option>Hausa</option><option>Igbo</option><option>Yorùbá</option><option>العربية</option><option>Français</option></select></label><a className="staff-top-button" href="/staff">Staff sign in&nbsp;↗</a></div></header>
  <main className="gateway-main">
    <section className="gateway-intro"><div><span className="gateway-kicker"><i></i> FNPH Kaduna Telepsychiatry</span><h1>Welcome</h1><p>Safe, structured psychiatric follow-up for eligible existing FNPH Kaduna patients—through a calm, private and connected care journey.</p><div className="gateway-standards"><span>Video-first consultations</span><span>Protected care pathway</span><span>24/7 support route</span></div><div className="review-note"><strong>Start your telepsychiatry journey</strong><p>Use your FNPH hospital number / EHR number to enrol. You must already be an FNPH Kaduna patient who has been assessed in person.</p></div></div><section className="portal-grid two" aria-label="Begin your telepsychiatry journey"><div className="portal-card patient hero-journey-card"><h2>Begin your telepsychiatry journey</h2><p>Use your FNPH hospital number / EHR number to enrol, complete the safety and consent steps, request a consultation and join your approved session.</p><a className="card-link" href="/enrol">Begin my telepsychiatry journey <b>→</b></a><a className="card-link secondary-link" href="/patients"><span className="already-enrolled">Already enrolled</span>? Sign in to continue</a><span className="portal-note"><strong>For existing FNPH Kaduna patients only.</strong><span className="emergency-note">This service is not for emergencies.</span></span></div></section></section>
    <div className="gateway-help"><div><b>Need help or support?</b><span> The FNPH helpdesk is available 24/7. Do not share your password or full payment details in ordinary chat.</span></div><a className="support-button" href="tel:08032722243">☎ 24/7 Help and Support</a></div>
    <section className="shared-foundation"><span>One trusted foundation</span><div><b>Secure identity</b><b>Clinical approvals</b><b>30-minute video-first care</b><b>Audio fallback</b><b>Auditable workflow</b></div></section>
  </main>
  <footer className="site-footer"><span>Federal Neuropsychiatric Hospital Kaduna · FNPH Kaduna Telepsychiatry</span><span>Care, privacy and clear guidance at every step</span></footer>
</div> }
